# Generated by Django 5.1.4 on 2025-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("done", "Done"), ("not done", "Not Done")],
                default="not done",
                max_length=20,
            ),
        ),
    ]
