# Generated by Django 5.1.4 on 2025-03-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_item_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="status",
        ),
    ]
