# Generated by Django 5.1.4 on 2025-03-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_remove_item_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="username",
            new_name="user",
        ),
    ]
