# Generated by Django 5.1.4 on 2025-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_rename_username_item_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("not done", "Not Done"),
                    ("in progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="not done",
                max_length=20,
            ),
        ),
    ]
